[package]
name = "bitpet-cli"
version = "0.1.0"
edition = "2024"
description = "CLI tool to create and manage your BitPet (https://bitpet.dev)"
authors = ["Rishabh Poddar <rishabh@trythis.app>"]

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
